# Generated by Django 5.0.6 on 2024-06-08 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('idagenda', models.IntegerField(primary_key=True, serialize=False)),
                ('notasadicionales', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coberturasalud',
            fields=[
                ('idcoberturasalud', models.IntegerField(primary_key=True, serialize=False)),
                ('coberturasalud', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'coberturasalud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corrientepsicologica',
            fields=[
                ('idcorrientepsicologica', models.IntegerField(primary_key=True, serialize=False)),
                ('corrientepsicologica', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'corrientepsicologica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diadisponible',
            fields=[
                ('iddiadisponible', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField()),
            ],
            options={
                'db_table': 'diadisponible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('iddiagnostico', models.IntegerField(primary_key=True, serialize=False)),
                ('diagnostico', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'diagnostico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadosesion',
            fields=[
                ('idestadosesion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'estadosesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadousuario',
            fields=[
                ('idestadousuario', models.IntegerField(primary_key=True, serialize=False)),
                ('estadousuario', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'estadousuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Generopsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idgoneropsicologo', models.IntegerField()),
                ('genero', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'generopsicologo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('idmensaje', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField()),
                ('contenido', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'mensaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodopago',
            fields=[
                ('idmetodopago', models.IntegerField(primary_key=True, serialize=False)),
                ('metodopago', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=128)),
                ('habilitado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'metodopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Motivosesion',
            fields=[
                ('idmotivosesion', models.IntegerField(primary_key=True, serialize=False)),
                ('motivosesion', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'motivosesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('idnotificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField()),
                ('asunto', models.CharField(max_length=128)),
                ('detalle', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'paciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pacientepsicologo',
            fields=[
                ('psicologo_idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente_idusuario', models.IntegerField()),
            ],
            options={
                'db_table': 'pacientepsicologo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idpago', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField()),
                ('montototal', models.IntegerField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Psicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroregistrolicencia', models.BigIntegerField(blank=True, null=True)),
                ('tarifasesion', models.IntegerField()),
            ],
            options={
                'db_table': 'psicologo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rangoetario',
            fields=[
                ('idrangoetario', models.IntegerField(primary_key=True, serialize=False)),
                ('rangoetario', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'rangoetario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rangoprecio',
            fields=[
                ('idrangoprecio', models.IntegerField(primary_key=True, serialize=False)),
                ('montominimo', models.IntegerField()),
                ('montomaximo', models.IntegerField()),
            ],
            options={
                'db_table': 'rangoprecio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('idresena', models.FloatField(primary_key=True, serialize=False)),
                ('puntuacion', models.BooleanField()),
                ('comentarios', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'resena',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('idsesion', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField()),
                ('notas', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'sesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Superusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'superusuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('idtest', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticketsoporte',
            fields=[
                ('idticketsoporte', models.IntegerField(primary_key=True, serialize=False)),
                ('fechahora', models.DateField()),
                ('contenido', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'ticketsoporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposesion',
            fields=[
                ('idtiposesion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'tiposesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=64)),
                ('tipousuario', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testpaciente',
            fields=[
                ('idtest', models.OneToOneField(db_column='idtest', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.test')),
                ('generopsicologo_idgoneropsicologo', models.IntegerField()),
            ],
            options={
                'db_table': 'testpaciente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testpsicologo',
            fields=[
                ('idtest', models.OneToOneField(db_column='idtest', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.test')),
            ],
            options={
                'db_table': 'testpsicologo',
                'managed': False,
            },
        ),
    ]
