# Generated by Django 5.0.6 on 2024-06-17 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_genero'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
    ]
