from django.contrib import admin
# Register your models here.
from .models import Agenda, Coberturasalud, Corrientepsicologica, Diagnostico, Diadisponible, Estadosesion, Estadousuario, Generopsicologo, Mensaje, Motivosesion, Metodopago, Notificacion, Paciente, Pacientepsicologo, Pago, Psicologo, Rangoetario, Rangoprecio, Resena, Sesion, Test, Testpaciente, Testpsicologo, Ticketsoporte, Tiposesion, Usuario


admin.site.register(Agenda)
admin.site.register(Coberturasalud)
admin.site.register(Corrientepsicologica)
admin.site.register(Diagnostico)
admin.site.register(Diadisponible)
admin.site.register(Estadosesion)
admin.site.register(Estadousuario)
admin.site.register(Generopsicologo)
admin.site.register(Mensaje)
admin.site.register(Motivosesion)
admin.site.register(Metodopago)
admin.site.register(Notificacion)
admin.site.register(Paciente)
admin.site.register(Pacientepsicologo)
admin.site.register(Pago)
admin.site.register(Psicologo)
admin.site.register(Rangoetario)
admin.site.register(Rangoprecio)
admin.site.register(Resena)
admin.site.register(Sesion)
admin.site.register(Test)
admin.site.register(Testpaciente)
admin.site.register(Testpsicologo)
admin.site.register(Ticketsoporte)
admin.site.register(Tiposesion)
admin.site.register(Usuario)
